version: '3.3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - '8008:80'
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: db-user
      WORDPRESS_DB_PASSWORD: db-password
